// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DesafioApiMelao.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20230112190958_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "7.0.2")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("DesafioApiMelao.Models.Tarefa", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasColumnName("Id");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("DataTarefa")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("DATETIME")
                    .HasColumnName("DataTarefa")
                    .HasComputedColumnSql("GetUtcDate()");

                b.Property<string>("Descricao")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("VARCHAR")
                    .HasColumnName("Descricao");

                b.Property<string>("Titulo")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("VARCHAR")
                    .HasColumnName("Titulo");

                b.HasKey("Id");

                b.HasIndex("Id");

                b.ToTable("Tarefas");
            });
#pragma warning restore 612, 618
    }
}
